[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v3.$major.$minor$patch_$prerelease"
version_scheme = "semver"
version = "0.1.0"
update_changelog_on_bump = true
major_version_zero = true
